credentials:
  usernames:
    admin:
      email: admin@mashroo3k.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: User
      logged_in: false
      name: Administrator
      password: $2b$12$sD1Lf7hv1QGFGcyou/urWeUCmznGZe6986I.Quke9lULMpusfF7o. # admin123
    safwat:
      email: safwat@mashroo3k.com
      failed_login_attempts: 0
      first_name: Safwat
      last_name: Rabea
      logged_in: false
      name: Safwat Rabea
      password: $2b$12$VTJVB/Bz2mLNYo3GDP/cIuOXC3iQ4bLLoaCma6Q2Ah81Bbpf7ZIjq # 123456

cookie:
  expiry_days: 1
  key: random_signature_key_123
  name: mashroo3k_brain
  
preauthorized:
  emails: []
