version: '3.8'

services:
  qdrant_server:
    image: qdrant/qdrant:latest
    container_name: qdrant_server
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_db:/qdrant/storage

  rag_app:
    build: .
    container_name: rag_app
    ports:
      - "8501:8501"
    depends_on:
      - qdrant_server
    env_file:
      - .env
    volumes:
      - ./data:/app/data
